I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 75, in script
    show monika doctor 1h at f43 zorder 1
Exception: Say has image attributes (u'1g',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 75, in script
    show monika doctor 1h at f43 zorder 1
  File "C:\Users\NZXT\Desktop\renpy-7.6.1-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\NZXT\Desktop\renpy-7.6.1-sdk/renpy/exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "C:\Users\NZXT\Desktop\renpy-7.6.1-sdk/renpy/character.py", line 1290, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\NZXT\Desktop\renpy-7.6.1-sdk/renpy/character.py", line 1109, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\NZXT\Desktop\renpy-7.6.1-sdk/renpy/character.py", line 1035, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes (u'1g',), but there's no image tag associated with the speaking character.

Windows-10-10.0.19041 AMD64
Ren'Py 7.6.1.23060707
DDLC - No More Time 0.0.1
Thu Jun 29 14:04:31 2023
