I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 273, in script call
    call gun_start
  File "game/gun-minigame.rpy", line 20, in script call
    call minigame
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 273, in script call
    call gun_start
  File "game/gun-minigame.rpy", line 20, in script call
    call minigame
ScriptError: could not find label 'minigame'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 273, in script call
    call gun_start
  File "game/gun-minigame.rpy", line 20, in script call
    call minigame
  File "renpy/ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 273, in script call
    call gun_start
  File "game/gun-minigame.rpy", line 20, in script call
    call minigame
  File "renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'minigame'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.6.1.23060707
DDLC - No More Time 0.0.1
Sat Jul  1 14:27:11 2023
